### ISSUE TITLE
Please make npm package

### ISSUE THREAD

**Issue by dionyziz** [bryanwoods/autolink-js#19]
This will allow it to be used from within node.js/io.js and with browserify.

**Comment by bryanwoods** [comment]
This sounds great -- any chance you could submit a pull request? I haven't worked much in node for a few years.

**Comment by bryanwoods** [comment]
@dionyziz :+1: https://www.npmjs.com/package/autlink-js
Let me know if you have any issues.

**Comment by dionyziz** [comment]
Thanks!

**Comment by axelson** [comment]
For future reference it looks like there's two packages on npm and the better one is https://www.npmjs.com/package/autolink-js (the other linked above has a typo in the name)
